### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by mnovozhylov** [ApiGen/ApiGen#1042]
Hi!

Having
```
"apigen/apigen": "dev-master",
"roave/better-reflection": "dev-master#c87d856"
```
I execute `vendor/apigen/apigen/bin/apigen generate src --destination docs_html` and get persistently the following fatal error:
```
vendor/apigen/apigen/bin/apigen generate src --destination docs_html
Parsing reflections (this may take a while)...
Fatal error: Uncaught TypeError: Return value of Roave\BetterReflection\Reflection\ReflectionClass::getShortName() must be of the type string, object returned in vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:178
Stack trace:
#0 vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(199): Roave\BetterReflection\Reflection\ReflectionClass->getShortName()
#1 vendor/roave/better-reflection/src/SourceLocator/Ast/Locator.php(98): Roave\BetterReflection\Reflection\ReflectionClass->getName()
#2 vendor/roave/better-reflection/src/SourceLocator/Ast/Locator.php(57): Roave\BetterReflection\SourceLocator\Ast\Locator->findInArray(Array, Object(Roave\BetterReflection\Identifier\Identifier))
#3 vendor/roave/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(50): Roave\BetterR in vendor/roave/better-reflection/src/Reflection/ReflectionClass.php on line 178
```
Any known issues with this or a workaround?

Thanks!

**Comment by mnovozhylov** [comment]
OK, I managed to fix it by removing the anchor, i.e. using ""roave/better-reflection": "dev-master".
You might want to recheck and update the README. So, I leave it open.

**Comment by Saibamen** [comment]
#1052

**Comment by alphadevx** [comment]
I can confirm I have the same issue running ApiGen on PHP 7.2, the PR from @Saibamen fixed it for me.

**Comment by ve3** [comment]
using `"roave/better-reflection": "dev-master"`
PHP 7.3
get this error

> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Roave\BetterReflection\SourceLocator\Ast\Locator": argument "$functionReflectorGetter" of method "__construct()" references class "Closure" but no such service exists. It cannot be auto-registered because it is from a different root namespace. in D:\my-work-spaces\ApiGen\vendor\symfony\dependency-injection\Compiler\DefinitionErrorExceptionPass.php on line 37
> 
> Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Roave\BetterReflection\SourceLocator\Ast\Locator": argument "$functionReflectorGetter" of method "__construct()" references class "Closure" but no such service exists. It cannot be auto-registered because it is from a different root namespace. in D:\my-work-spaces\ApiGen\vendor\symfony\dependency-injection\Compiler\DefinitionErrorExceptionPass.php on line 37

**Comment by mihitha** [comment]
Same Problem still,

using "roave/better-reflection": "dev-master"
PHP 7.3.06, Ubuntu 18.04
```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Roave\BetterReflection\SourceLocator\Ast\Locator": argument "$functionReflectorGetter" of method "__construct()" references class "Closure" but no such service exists. It cannot be auto-registered because it is from a different root namespace. in /Lawcadia_API/GIT_CODE/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:37
Stack trace:
#0 /Lawcadia_API/GIT_CODE/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /Lawcadia_API/GIT_CODE/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(30): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /Lawcadia_API/GIT_CODE/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(39 in /Lawcadia_API/GIT_CODE/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 37
```

**Comment by mihitha** [comment]
Same Problem still,

using 
```
"apigen/apigen": "dev-master"
"roave/better-reflection": "dev-master"
```
PHP 7.3.06, Ubuntu 18.04
```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Roave\BetterReflection\SourceLocator\Ast\Locator": argument "$functionReflectorGetter" of method "__construct()" references class "Closure" but no such service exists. It cannot be auto-registered because it is from a different root namespace. in /vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:37
Stack trace:
#0 /vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(30): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(39 in /vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 37
```

**Comment by nanoninja** [comment]
I have the same problem. I do not stop fighting with depandencies for it to work but it's tiring. It would be nice to have some stability.

PHP version :

```sh
PHP 7.3.6 (cli) (built: Jun 11 2019 02:03:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethan
```

Using :

```sh
 "apigen/apigen": "dev-master",
 "phpmd/phpmd": "@stable",
 "phpunit/phpunit": "^7.0",
 "roave/better-reflection": "dev-master",
 "squizlabs/php_codesniffer": "3.*"
```

Output :

```sh
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Roave\Be
tterReflection\SourceLocator\Ast\Locator": argument "$functionReflectorGetter" of method "__construct()" references class
 "Closure" but no such service exists. It cannot be auto-registered because it is from a different root namespace. in /va
r/www/html/app/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 37

Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Roave\BetterReflection\SourceL
ocator\Ast\Locator": argument "$functionReflectorGetter" of method "__construct()" references class "Closure" but no such
 service exists. It cannot be auto-registered because it is from a different root namespace. in /var/www/html/app/vendor/
symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 37

Call Stack:
    0.0007     391128   1. {main}() /var/www/html/app/vendor/apigen/apigen/bin/apigen:0
    0.0484    2452512   2. ApiGen\DependencyInjection\Container\ContainerFactory->create() /var/www/html/app/vendor/apige
n/apigen/bin/apigen:12
    0.0661    2648960   3. ApiGen\DependencyInjection\AppKernel->boot() /var/www/html/app/vendor/apigen/apigen/src/Depend
encyInjection/Container/ContainerFactory.php:13
    0.0662    2651432   4. ApiGen\DependencyInjection\AppKernel->initializeContainer() /var/www/html/app/vendor/symfony/h
ttp-kernel/Kernel.php:135
    2.0323    6857384   5. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /var/www/html/app/vendor/sym
fony/http-kernel/Kernel.php:643
    2.0950    6861328   6. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /var/www/html/app/vendor/sy
mfony/dependency-injection/ContainerBuilder.php:790
```

**Comment by ianterrell** [comment]
Same experience on Mac OS X.

```
$ php -version
PHP 7.3.9 (cli) (built: Nov  9 2019 08:08:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
```

```
$ vendor/bin/apigen generate ../plugin --destination docs

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Roave\BetterReflection\SourceLocator\Ast\Locator": argument "$functionReflectorGetter" of method "__construct()" references class "Closure" but no such service exists. It cannot be auto-registered because it is from a different root namespace. in /project/doc/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:37
Stack trace:
#0 /project/doc/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /project/doc/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(30): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /Users/ian.terrell/src/wooc in /project/doc/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 37
```

**Comment by fmp777** [comment]
+1 same autowire error on ubuntu php7.2 after removing the commit anchor and updating composer - apigen not functioning at all

**Comment by alvaro-octal** [comment]
Fixed this via https://github.com/ApiGen/ApiGen/issues/1065#issuecomment-626875552

**Comment by JanTvrdik** [comment]
Not relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
