### ISSUE TITLE
Better-Reflection dev-master#c87d856 is no more working

### ISSUE THREAD

**Issue by vipinjn24** [ApiGen/ApiGen#1046]
`"roave/better-reflection": "dev-master#c87d856"` is no more working and we have to use below.

`"roave/better-reflection": "dev-master"`

Please create a new PR to update the readme.md

**Comment by simpsonw** [comment]
`"roave/better-reflection": "dev-master#c87d856"` and `"apigen/apigen": "dev-master"` don't appear to be working for me:

```
$ vendor/bin/apigen generate src/ --destination docs/apigen/
Parsing reflections (this may take a while)...PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Roave\BetterReflection\SourceLocator\Reflection\SourceStubber::addDocComment() must be an instance of PhpParser\BuilderAbstract, instance of PhpParser\Builder\Interface_ given, called in /var/www/html/project/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 63 and defined in /var/www/html/ual-payments/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php:97
Stack trace:
#0 /var/www/html/project/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php(63): Roave\BetterReflection\SourceLocator\Reflection\SourceStubber->addDocComment(Object(PhpParser\Builder\Interface_), Object(ReflectionClass))
#1 /var/www/html/project/vendor/roave/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(53): Roave\BetterReflection\SourceLocator\Reflection\SourceStubber->__invoke(Object(ReflectionClass))
#2 /var/www/html/project/vendor/roave/better-reflection/src/SourceLocat in /var/www/html/ual-payments/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 97
```
Using `"roave/better-reflection": "dev-master"` gives me an exception when I try to run `composer update`:

```$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals

                                                                 
  [InvalidArgumentException]                                     
  Package is not installed: roave/better-reflection-9999999-dev  
                                                                 

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [
--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] 
[--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

**Comment by giansalex** [comment]
`"roave/better-reflection": "dev-master#ce9d784"` worked for me

**Comment by PSIKYO** [comment]
The sources in "\packages\BetterReflection\src\SourceLocator\*" should all be updated to catch up the newest "roave/better-reflection".

**Comment by JanTvrdik** [comment]
Not relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
