### ISSUE TITLE
Uncaught TypeError  Argument 1 passed to SourceStubber::addDocComment() 

### ISSUE THREAD

**Issue by claytron5000** [ApiGen/ApiGen#1067]
composer:
```
        "apigen/apigen": "dev-master",
        "roave/better-reflection": "dev-master#c87d856"
```

command:
```
php vendor/bin/apigen generate common/api/restful/v1 --destination ./schooladmin/setup 
```

error:
```
 Uncaught TypeError: Argument 1 passed to Roave\BetterReflection\SourceLocator\Reflection\SourceStubber::addDocComment() must be an instance of PhpParser\BuilderAbstract, instance of PhpParser\Builder\Interface_ given, called in /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 63 and defined in /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php:97
Stack trace:
#0 /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php(63): Roave\BetterReflection\SourceLocator\Reflection\SourceStubber->addDocComment(Object(PhpParser\Builder\Interface_), Object(ReflectionClass))
#1 /app/vendor/roave/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(53): Roave\BetterReflection\SourceLocator\Reflection\SourceStubber->__invoke(Object(ReflectionClass))
#2 /app/vendor/roave/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(45): Roave\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->cre in /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 97

Fatal error: Uncaught TypeError: Argument 1 passed to Roave\BetterReflection\SourceLocator\Reflection\SourceStubber::addDocComment() must be an instance of PhpParser\BuilderAbstract, instance of PhpParser\Builder\Interface_ given, called in /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 63 and defined in /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 97

TypeError: Argument 1 passed to Roave\BetterReflection\SourceLocator\Reflection\SourceStubber::addDocComment() must be an instance of PhpParser\BuilderAbstract, instance of PhpParser\Builder\Interface_ given, called in /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 63 in /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 97

Call Stack:
    0.0036     390192   1. {main}() /app/vendor/apigen/apigen/bin/apigen:0
    0.4313   10663544   2. Symfony\Component\Console\Application->run() /app/vendor/apigen/apigen/bin/apigen:16
    0.4638   10763432   3. Symfony\Component\Console\Application->doRun() /app/vendor/symfony/console/Application.php:147
    0.4693   10768616   4. Symfony\Component\Console\Application->doRunCommand() /app/vendor/symfony/console/Application.php:254
    0.4693   10768616   5. ApiGen\Console\Command\GenerateCommand->run() /app/vendor/symfony/console/Application.php:963
    0.4713   10770864   6. ApiGen\Console\Command\GenerateCommand->execute() /app/vendor/symfony/console/Command/Command.php:255
    0.4778   10774880   7. ApiGen\Application\ApiGenApplication->runCommand() /app/vendor/apigen/apigen/src/Console/Command/GenerateCommand.php:61
    0.4835   10776144   8. ApiGen\Reflection\Parser\Parser->parseFilesAndDirectories() /app/vendor/apigen/apigen/src/Application/ApiGenApplication.php:64
    0.5095   11531768   9. ApiGen\Reflection\Parser\Parser->parseClassElements() /app/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:59
    0.5120   11538728  10. ApiGen\Reflection\Parser\Parser->transformBetterClassInterfaceAndTraitReflections() /app/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:190
    2.6775   18863768  11. ApiGen\Reflection\Parser\Parser->resolveParentClassesInterfacesAndTraits() /app/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:102
   16.9159   21644096  12. ApiGen\Reflection\Parser\Parser->resolveParentInterfaces() /app/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:120
   25.1820   23254776  13. Roave\BetterReflection\Reflection\ReflectionClass->getInterfaces() /app/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:156
   25.1821   23255448  14. array_map() /app/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1046
   25.1821   23255504  15. Roave\BetterReflection\Reflection\ReflectionClass->Roave\BetterReflection\Reflection\{closure}() /app/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1046
   25.1821   23255504  16. Roave\BetterReflection\Reflection\ReflectionClass->getCurrentClassImplementedInterfacesIndexedByName() /app/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1044
   25.1821   23255800  17. array_map() /app/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1200
   25.1821   23255856  18. Roave\BetterReflection\Reflection\ReflectionClass->Roave\BetterReflection\Reflection\{closure}() /app/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1200
   25.1821   23255856  19. Roave\BetterReflection\Reflection\ReflectionClass->reflectClassForNamedNode() /app/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1197
   25.1821   23255832  20. Roave\BetterReflection\Reflector\ClassReflector->reflect() /app/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:954
   25.1822   23255968  21. Roave\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier() /app/vendor/roave/better-reflection/src/Reflector/ClassReflector.php:37
   25.9248   23455336  22. Roave\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier() /app/vendor/roave/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php:37
   25.9250   23455336  23. Roave\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->locateIdentifier() /app/vendor/roave/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php:37
   25.9250   23455336  24. Roave\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->createLocatedSource() /app/vendor/roave/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php:45
   25.9271   23459072  25. Roave\BetterReflection\SourceLocator\Reflection\SourceStubber->__invoke() /app/vendor/roave/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php:53
   25.9320   23471136  26. Roave\BetterReflection\SourceLocator\Reflection\SourceStubber->addDocComment() /app/vendor/roave/better-reflection/src/SourceLocator/Reflection/SourceStubber.php:63
```

**Comment by JanTvrdik** [comment]
No longer relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha.
