### ISSUE TITLE
Error when using current master HEAD f403ac8c7e

### ISSUE THREAD

**Issue by ADmad** [apigen/apigen#483]
Running `./bin/apigen generate --debug` from apigen folder generates following error.

```
$ ./bin/apigen generate --debug
exception 'ErrorException' with message 'Argument 1 passed to ApiGen\Generator\GeneratorQueue::addToQueue() must implement interface ApiGen\Generator\TemplateGenerator, instance of ApiGen\Generator\TemplateGenerators\Loaders\NamespaceAndPackageLoader given, called in /tmp/_apigen.temp/cache/Nette.Configurator/c3ef0a1b0254ca3e88ea4ca19c9c3310.php on line 456 and defined' in /srv/sites/apigen/src/ApiGen/Generator/GeneratorQueue.php:44
Stack trace:
#0 /srv/sites/apigen/src/ApiGen/Generator/GeneratorQueue.php(44): Tracy\Debugger::_errorHandler(4096, 'Argument 1 pass...', '/srv/sites/cake...', 44, Array)
#1 /tmp/_apigen.temp/cache/Nette.Configurator/c3ef0a1b0254ca3e88ea4ca19c9c3310.php(456): ApiGen\Generator\GeneratorQueue->addToQueue(Object(ApiGen\Generator\TemplateGenerators\Loaders\NamespaceAndPackageLoader))
#2 [internal function]: SystemContainer->createService__26_ApiGen_Generator_GeneratorQueue()
#3 /srv/sites/apigen/vendor/nette/di/src/DI/Container.php(152): call_user_func_array(Array, Array)
#4 /srv/sites/apigen/vendor/nette/di/src/DI/Container.php(102): Nette\DI\Container->createService('26_ApiGen_Gener...')
#5 /tmp/_apigen.temp/cache/Nette.Configurator/c3ef0a1b0254ca3e88ea4ca19c9c3310.php(953): Nette\DI\Container->getService('26_ApiGen_Gener...')
#6 [internal function]: SystemContainer->createService__39()
#7 /srv/sites/apigen/vendor/nette/di/src/DI/Container.php(152): call_user_func_array(Array, Array)
#8 /srv/sites/apigen/vendor/nette/di/src/DI/Container.php(102): Nette\DI\Container->createService('39')
#9 /tmp/_apigen.temp/cache/Nette.Configurator/c3ef0a1b0254ca3e88ea4ca19c9c3310.php(975): Nette\DI\Container->getService('39')
#10 [internal function]: SystemContainer->createService__41()
#11 /srv/sites/apigen/vendor/nette/di/src/DI/Container.php(152): call_user_func_array(Array, Array)
#12 /srv/sites/apigen/vendor/nette/di/src/DI/Container.php(102): Nette\DI\Container->createService('41')
#13 /srv/sites/apigen/vendor/nette/di/src/DI/Container.php(184): Nette\DI\Container->getService('41')
#14 /srv/sites/apigen/src/apigen.php(54): Nette\DI\Container->getByType('ApiGen\Console\...')
#15 /srv/sites/apigen/bin/apigen(4): require('/srv/sites/cake...')
#16 {main}

```

I ran composer update beforehand.

**Comment by TomasVotruba** [comment]
@ADmad Closing issue then.

For `$groupBy`, it's never defined in the template, thus the error.
Maybe you can try `$config->groupBy`.

**Comment by ADmad** [comment]
@TomasVotruba Yup the original issue is resolved.

Regarding the `$groupBy` in template, it's used on both the [default](https://github.com/apigen/apigen/blob/master/src/templates/default/%40layout.latte#L37) and bootstrap themes so I simply copied that assuming it be being set.

**Comment by TomasVotruba** [comment]
@ADmad I see. Open new issue then, please. So it won't get lost.
