### ISSUE TITLE
Stylesheet not generated

### ISSUE THREAD

**Issue by FlTr** [ApiGen/ApiGen#505]
On linux (Raspian) bootstrap.min.css isn't generated and a random number is missing.
HTML source with linux:
````html
<link rel="stylesheet" href="resources/bootstrap.min.css">
<link rel="stylesheet" href="resources/style.css?e99947befd7bf673c6b43ff75e9e0f170c88a60e">
````

HTML source with windows:
````html
<link rel="stylesheet" href="resources/bootstrap.min.css?08b23951ef4599ca9cbf1f902d0e8290c9653ddd">
<link rel="stylesheet" href="resources/style.css?062e9e59e0b8c44fbaaded5b7ffc21f907b78669">
````

**Comment by TomasVotruba** [comment]
Do you know any more details how this is caused?

**Comment by FlTr** [comment]
Not really. Tried it several times.
With two different windows machines it  works fine.

What seems to be a bit strange, run with debug mode ````~/apigen generate --debug```` causes an exception:

````
exception 'ErrorException' with message 'unlink(/var/www/lti/docu/phpapi/resources/style.css): Permission denied' in phar:///home/pi/apigen/src/ApiGen/FileSystem/FileSystem.php:64
Stack trace:
#0 [internal function]: Tracy\Debugger::_errorHandler(2, 'unlink(/var/www...', 'phar:///home/pi...', 64, Array)
#1 phar:///home/pi/apigen/src/ApiGen/FileSystem/FileSystem.php(64): unlink('/var/www/lti/do...')
#2 phar:///home/pi/apigen/src/ApiGen/Command/GenerateCommand.php(171): ApiGen\FileSystem\FileSystem::purgeDir('/var/www/lti/do...')
#3 phar:///home/pi/apigen/src/ApiGen/Command/GenerateCommand.php(141): ApiGen\Command\GenerateCommand->generate(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///home/pi/apigen/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(252): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///home/pi/apigen/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///home/pi/apigen/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateCommand), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///home/pi/apigen/src/ApiGen/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///home/pi/apigen/vendor/symfony/console/Symfony/Component/Console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///home/pi/apigen/src/ApiGen/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#10 phar:///home/pi/apigen/src/apigen.php(52): ApiGen\Console\Application->run()
#11 /home/pi/apigen(12): require('phar:///home/pi...')
#12 {main}
````

**Comment by FlTr** [comment]
Ok, i found the problem. Apigen requires root.

Without root but with existing destination directory:
````bash
/var/www/lti $ ~/apigen generate
Scanning sources and parsing
Found 1 classes, 0 constants, 0 functions and 0 PHP internal classes
Generating API documentation
100 % - Finished!
````
In debug mode:
````
/var/www/lti $ ~/apigen generate --debug
Scanning sources and parsing
Found 1 classes, 0 constants, 0 functions and 0 PHP internal classes
exception 'ErrorException' with message 'unlink(/var/www/lti/docu/phpapi/resources/style.css): Permission denied' in phar:///home/pi/apigen/src/ApiGen/FileSystem/FileSystem.php:64
Stack trace:
#0 [internal function]: Tracy\Debugger::_errorHandler(2, 'unlink(/var/www...', 'phar:///home/pi...', 64, Array)
#1 phar:///home/pi/apigen/src/ApiGen/FileSystem/FileSystem.php(64): unlink('/var/www/lti/do...')
#2 phar:///home/pi/apigen/src/ApiGen/Command/GenerateCommand.php(171): ApiGen\FileSystem\FileSystem::purgeDir('/var/www/lti/do...')
#3 phar:///home/pi/apigen/src/ApiGen/Command/GenerateCommand.php(141): ApiGen\Command\GenerateCommand->generate(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///home/pi/apigen/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(252): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///home/pi/apigen/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///home/pi/apigen/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateCommand), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///home/pi/apigen/src/ApiGen/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///home/pi/apigen/vendor/symfony/console/Symfony/Component/Console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///home/pi/apigen/src/ApiGen/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#10 phar:///home/pi/apigen/src/apigen.php(52): ApiGen\Console\Application->run()
#11 /home/pi/apigen(12): require('phar:///home/pi...')
#12 {main}
````

With root, all is generated correct
````bash
/var/www/lti $ sudo ~/apigen generate --debug
Scanning sources and parsing
Found 1 classes, 0 constants, 0 functions and 0 PHP internal classes
Generating API documentation
 3/3 [============================] 100% 21 secs/21 secs 9.2 MiB - Finished!
````

Think it would be nice, if running without root an error should occur and not telling "100% - Finished!". An error occur if the destination directory doesn't exist.

**Comment by TomasVotruba** [comment]
That seems strange. If `/var/www/lti/docu/phpapi/resources/style.css` is created, it should be deletable by the same used.

**What's the output for this?**

Prepare `SomeClass.php` with content:

```php
<?php

class SomeClass 
{

}
```

then run:

```
wget http://apigen.org/apigen.phar 
php apigen.phar generate -s . -d dest --debug
php apigen.phar generate -s . -d dest --debug
```

**Comment by FlTr** [comment]
Ok, i tried it. No problems.

I tested some things by myself.

i think the problem occured because originally it was generated with a global installation of apigen and then regenerated with home installation, Think something went wrong with root-rights.

Deleted everything, installed it global again, run -> OK

Think could be closed, more or less my fault.
Nevertheless telling "100% - Finished" but an exception occured is something strange.

By the way, making apigen executable should be added.

**Comment by TomasVotruba** [comment]
I see. Silent exceptions are not really helpful.

Could provide fix, so exception from copying can get to the output?

It's probably [`purgeDir()` call in `GenerateCommand`](https://github.com/ApiGen/ApiGen/blob/552a0d046eda2162e8662c0f444f601bba707460/src/Command/GenerateCommand.php#L171). Then [`unlink()` is called](https://github.com/ApiGen/ApiGen/blob/552a0d046eda2162e8662c0f444f601bba707460/src/FileSystem/FileSystem.php#L64) in the method.

---

What excatly do you mean by "making apigen executable should be added"?

**Comment by FlTr** [comment]
````
$ mv apigen.phar /usr/local/bin/apigen
$ chmod +x /usr/local/bin/apigen
````

**Comment by TomasVotruba** [comment]
I see. Could you send PR to complete it here? https://github.com/ApiGen/ApiGen/blob/master/doc/installation.md

**Comment by TomasVotruba** [comment]
I've updated the wiki, closing: https://github.com/ApiGen/ApiGen/wiki/installation-on-unix
