### ISSUE TITLE
Unexpected token found

### ISSUE THREAD

**Issue by marcovtwout** [ApiGen/ApiGen#510]
I have included the latest stable version through Composer, and am trying to generate docs for a project.

The output concludes:
```
Scanning sources and parsing

Unexpected token found.
```

How would I go about finding the cause of this issue? Can I enable a debug mode or get a stack trace? There is no documentation about this. And what does the error message mean?

**Comment by TomasVotruba** [comment]
Try running command with `--debug` option. 

If you ran command with `--help` option, you can see all possible options.

**Comment by marcovtwout** [comment]
It looks like the debug parameter triggers another error. I am on Windows and this is the output:

```
S:\www\dgbc_qa\docs>..\application\vendor\bin\apigen generate --debug
exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in S:\www\test\application\vendor\apigen\apigen\src\ApiGen\Configuration\ConfigurationOptionsResolver.php:181
Stack trace:
#0 S:\www\test\application\vendor\apigen\apigen\src\ApiGen\Configuration\ConfigurationOptionsResolver.php(181): Tracy\Debugger::_errorHandler(2, 'Invalid argumen...', 'S:\www\test\...', 181, Array)
#1 S:\www\test\application\vendor\symfony\options-resolver\Symfony\Component\OptionsResolver\OptionsResolver.php(932): ApiGen\Configuration\ConfigurationOptionsResolver->ApiGen\Configuration\{closure}(Object(Symfony\Component\OptionsResolver\OptionsResolver), NULL)
#2 S:\www\test\application\vendor\symfony\options-resolver\Symfony\Component\OptionsResolver\OptionsResolver.php(769): Symfony\Component\OptionsResolver\OptionsResolver->offsetGet('skipDocPath')
#3 S:\www\test\application\vendor\apigen\apigen\src\ApiGen\Configuration\ConfigurationOptionsResolver.php(97): Symfony\Component\OptionsResolver\OptionsResolver->resolve(Array)
#4 S:\www\test\application\vendor\apigen\apigen\src\ApiGen\Configuration\Configuration.php(55): ApiGen\Configuration\ConfigurationOptionsResolver->resolve(Array)
#5 S:\www\test\application\vendor\apigen\apigen\src\ApiGen\Command\GenerateCommand.php(206): ApiGen\Configuration\Configuration->resolveOptions(Array)
#6 S:\www\test\application\vendor\apigen\apigen\src\ApiGen\Command\GenerateCommand.php(139): ApiGen\Command\GenerateCommand->prepareOptions(Array)
#7 S:\www\test\application\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 S:\www\test\application\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 S:\www\test\application\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateCommand), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 S:\www\test\application\vendor\apigen\apigen\src\ApiGen\Console\Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 S:\www\test\application\vendor\symfony\console\Symfony\Component\Console\Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 S:\www\test\application\vendor\apigen\apigen\src\ApiGen\Console\Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#13 S:\www\test\application\vendor\apigen\apigen\src\apigen.php(52): ApiGen\Console\Application->run()
#14 S:\www\test\application\vendor\apigen\apigen\bin\apigen(4): require('S:\www\test\...')
#15 {main}
```

**Comment by marcovtwout** [comment]
Also, maybe you could write a quick note about contributing and the debug parameter, in your README.md or in a separate document, like this one for example: https://github.com/rocketeers/rocketeer/blob/master/CONTRIBUTING.md

**Comment by carltondickson** [comment]
Seeing the same issue but unfortunately the --debug command doesn't provide any extra information about which line is problematic

```
10:01:52 ~$ apigen generate --source /opt/project/ --destination ~/docs/ --debug
Scanning sources and parsing

Unexpected token found.

11:37:59 ~$ php -v
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

11:38:01 ~$ apigen -V
ApiGen version 4.0.0

11:39:44 ~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
```

**Comment by langeland** [comment]
I get the same error when generating api for TYPO3 CMS version 7.. It seems to be an issue with `token_get_all()` that does not support php 5.5.
On a line like this:
`$obj = \Foo\GeneralUtility::makeInstance(\Foo\Bar::class);`

we get something like (note the T_CLASS):

```
    [2] => Array
        (
            [0] => T_VARIABLE
            [1] => $obj
            [2] => 3
        )

    [3] => Array
        (
            [0] => T_WHITESPACE
            [1] =>  
            [2] => 3
        )

    [4] => =
    [5] => Array
        (
            [0] => T_WHITESPACE
            [1] =>  
            [2] => 3
        )

    [6] => Array
        (
            [0] => T_NS_SEPARATOR
            [1] => \
            [2] => 3
        )

    [7] => Array
        (
            [0] => T_STRING
            [1] => Foo
            [2] => 3
        )

    [8] => Array
        (
            [0] => T_NS_SEPARATOR
            [1] => \
            [2] => 3
        )

    [9] => Array
        (
            [0] => T_STRING
            [1] => GeneralUtility
            [2] => 3
        )

    [10] => Array
        (
            [0] => T_DOUBLE_COLON
            [1] => ::
            [2] => 3
        )

    [11] => Array
        (
            [0] => T_STRING
            [1] => makeInstance
            [2] => 3
        )

    [12] => (
    [13] => Array
        (
            [0] => T_NS_SEPARATOR
            [1] => \
            [2] => 3
        )

    [14] => Array
        (
            [0] => T_STRING
            [1] => Foo
            [2] => 3
        )

    [15] => Array
        (
            [0] => T_NS_SEPARATOR
            [1] => \
            [2] => 3
        )

    [16] => Array
        (
            [0] => T_STRING
            [1] => Bar
            [2] => 3
        )

    [17] => Array
        (
            [0] => T_DOUBLE_COLON
            [1] => ::
            [2] => 3
        )

    [18] => Array
        (
            [0] => T_CLASS
            [1] => class
            [2] => 3
        )

    [19] => )
    [20] => ;
```

Im not sure how to handle...

**Comment by TomasVotruba** [comment]
Thanks for detailed reports guy. It helps me to narrow the broken part.

I'm working on this ATM on [TokenReflection](https://github.com/ApiGen/TokenReflection) repo fork. It should use [nikic\PHP-Parser](https://github.com/nikic/PHP-Parser) to prevent such errors.

**Comment by TomasVotruba** [comment]
@marcovtwout Thanks for "contributing" suggestion. It's been added. Also feel free to open new issues for such separated problems/idea.

**Comment by marcovtwout** [comment]
Excellent. Ofcourse, people can also contribute by reporting issues. Maybe you can insert a chapter on top with some guidelines for that as well, such as: test on latest master, use --debug flag, etc.

**Comment by TomasVotruba** [comment]
@marcovtwout Could you send PR with proposal pls?

**Comment by marcovtwout** [comment]
Done: https://github.com/ApiGen/ApiGen/pull/535

**Comment by TomasVotruba** [comment]
Closing as this is issue in [TokenReflection](https://github.com/Andrewsville/PHP-Token-Reflection)

**Comment by tmquang6805** [comment]
I have same issue, enabled `--debug`, but nothing to show

```
apigen generate -s "/home/quangtm/workspace/co-api" -d "/home/quangtm/Documents/api-co-docs" --debug
Scanning sources and parsing

Unexpected token found.
```

More information about apigen and PHP version
```
apigen -V
ApiGen version 4.1.0
```

```
php --version
PHP 5.6.7 (cli) (built: Apr  1 2015 14:26:42) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```

What wrong with it, and how can I generate my API Docs

**Comment by TomasVotruba** [comment]
@tmquang6805 Hey, see my last message. This is bug in another library. I'm working in it's fork, but it will take a while.

I'd recommend you finding the file in your project causing this error, using `--source` option to more specific locations.

**Comment by enumag** [comment]
@TomasVotruba Same bug here. How is the TokenReflection fork going? Your link to the fork does not work anymore.

**Comment by TomasVotruba** [comment]
@enumag I do not maintain ApiGen anymore since June.

**Comment by enumag** [comment]
@TomasVotruba I know, I'm just curious about in what state you left the new https://github.com/ApiGen/ElementReflection library (you're its only contributor).

**Comment by TomasVotruba** [comment]
@enumag well it's WIP, never tried in ApiGen main package. I cannot tell you more than tests.

I'd recommend using this package: https://github.com/Roave/BetterReflection
It's modern and maintained.

**Comment by onedal88** [comment]
For me, actually failed on code with code *return type declarations* (PHP7).
Symfony console option `--debug` has no effect.

**Comment by netroby** [comment]
Still got the same problem --debug has no effect

**Comment by netroby** [comment]
http://php.net/manual/en/migration70.new-features.php 
because apigen does not support return type declare

**Comment by netroby** [comment]
see https://github.com/ApiGen/ApiGen/issues/766

**Comment by marcelognunez11** [comment]
look for a ; in the modules.....
Example: function myfunc()
Must be: function myfunc();
Mainly in implements classes...

**Comment by shivapoudel** [comment]
@TomasVotruba Is this still work in progress :)

**Comment by pierrejochem** [comment]
Any news how to fix this in detail or how to replace the lib?

**Comment by TomasVotruba** [comment]
This project is not maintained anymore

**Comment by POPSuL** [comment]
@TomasVotruba you talking about v4.0, or generally about this project?

**Comment by TomasVotruba** [comment]
Generally. I left before 5.0 was tagged stable, and current maintainer left a few weeks after that.

**Comment by POPSuL** [comment]
Ohhhh... But stable version is not perfect... We need at least that pr https://github.com/ApiGen/ApiGen/pull/1038 :(
I can't use v5.0 cuz that says to me "wait for 1 day for finish" and eat more than 5GB of RAM for project which have ~20kCLOC...

**Comment by POPSuL** [comment]
We need new maintainer =(

**Comment by TomasVotruba** [comment]
> We need new maintainer =(

That's the correct answer :)
