### ISSUE TITLE
Howto update a custom template from 2.8.0 to 4.0.0 ?

### ISSUE THREAD

**Issue by redaxmedia** [apigen/ApiGen#516]
Hello folks,

congrats to your fresh 4.0.0 release - keep on your good work.

I just gave it a try using the CLI.

It was a bit confusing that I had to use "generate --help" instead of "--help" to print all parameter, maby you just print everything instead of that trick. But that is not the issue...

Months ago I spend a lot of time to a custom template located here: https://github.com/redaxmedia/redaxscript-apigen-template ... it seems that release 4.0.0 does not understand the old <code>config.neon</code> format, please provide me a guide to make the old template work.

The command:

<pre>
php vendor/bin/apigen generate --template-config vendor/redaxmedia/redaxscript-apigen-template/config.neon --source Config.php --source includes --destination ../redaxscript-api/base</pre>

Returns the following:

<pre>
exception 'ErrorException' with message 'Undefined index: template' in /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Configuration/Theme/ThemeConfigOptionsResolver.php:163
Stack trace:
#0 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Configuration/Theme/ThemeConfigOptionsResolver.php(163): Tracy\Debugger::_errorHandler(8, 'Undefined index...', '/media/WIP/reda...', 163, Array)
#1 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Configuration/Theme/ThemeConfigOptionsResolver.php(151): ApiGen\Configuration\Theme\ThemeConfigOptionsResolver->makeTemplatePathsAbsolute(Array, Object(Symfony\Component\OptionsResolver\OptionsResolver))
#2 /media/WIP/redaxscript/vendor/symfony/options-resolver/Symfony/Component/OptionsResolver/OptionsResolver.php(932): ApiGen\Configuration\Theme\ThemeConfigOptionsResolver->ApiGen\Configuration\Theme\{closure}(Object(Symfony\Component\OptionsResolver\OptionsResolver), Array)
#3 /media/WIP/redaxscript/vendor/symfony/options-resolver/Symfony/Component/OptionsResolver/OptionsResolver.php(769): Symfony\Component\OptionsResolver\OptionsResolver->offsetGet('templates')
#4 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Configuration/Theme/ThemeConfigOptionsResolver.php(129): Symfony\Component\OptionsResolver\OptionsResolver->resolve(Array)
#5 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Configuration/Theme/ThemeConfig.php(57): ApiGen\Configuration\Theme\ThemeConfigOptionsResolver->resolve(Array)
#6 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Configuration/ConfigurationOptionsResolver.php(115): ApiGen\Configuration\Theme\ThemeConfig->getOptions()
#7 /media/WIP/redaxscript/vendor/symfony/options-resolver/Symfony/Component/OptionsResolver/OptionsResolver.php(836): ApiGen\Configuration\ConfigurationOptionsResolver->ApiGen\Configuration\{closure}(Object(Symfony\Component\OptionsResolver\OptionsResolver), NULL)
#8 /media/WIP/redaxscript/vendor/symfony/options-resolver/Symfony/Component/OptionsResolver/OptionsResolver.php(769): Symfony\Component\OptionsResolver\OptionsResolver->offsetGet('template')
#9 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Configuration/ConfigurationOptionsResolver.php(97): Symfony\Component\OptionsResolver\OptionsResolver->resolve(Array)
#10 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Configuration/Configuration.php(55): ApiGen\Configuration\ConfigurationOptionsResolver->resolve(Array)
#11 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Command/GenerateCommand.php(206): ApiGen\Configuration\Configuration->resolveOptions(Array)
#12 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Command/GenerateCommand.php(139): ApiGen\Command\GenerateCommand->prepareOptions(Array)
#13 /media/WIP/redaxscript/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /media/WIP/redaxscript/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /media/WIP/redaxscript/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateCommand), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /media/WIP/redaxscript/vendor/symfony/console/Symfony/Component/Console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /media/WIP/redaxscript/vendor/apigen/apigen/src/ApiGen/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#19 /media/WIP/redaxscript/vendor/apigen/apigen/src/apigen.php(52): ApiGen\Console\Application->run()
#20 /media/WIP/redaxscript/vendor/apigen/apigen/bin/apigen(4): require('/media/WIP/reda...')
#21 {main}
redaxmedia@anonymous:/media/WIP/redaxscript$ 
</pre>

**Comment by redaxmedia** [comment]
Please respond, how should a <code>config.neon</code> for 4.0.0 look like?

**Comment by redaxmedia** [comment]
Thank you for not providing support and lack of documentation. I'm kind of pissed off using your software for now...

Anyway, this is my config.neon now... I had do search your option handling to understand what changed... :-1: 

<code>
resources:
	latte/resources: resources
templates:
	overview:
		filename: index.html
		template: latte/overview.latte
	combined:
		filename: resources/combined.js
		template: latte/combined.js.latte
	elementlist:
		filename: elementlist.js
		template: latte/elementlist.js.latte
	404:
		filename: 404.html
		template: latte/404.latte
	package:
		filename: package-%s.html
		template: latte/package.latte
	namespace:
		filename: namespace-%s.html
		template: latte/namespace.latte
	class:
		filename: class-%s.html
		template: latte/class.latte
	constant:
		filename: constant-%s.html
		template: latte/constant.latte
	function:
		filename: function-%s.html
		template: latte/function.latte
	source:
		filename: source-%s.html
		template: latte/source.latte
	tree:
		filename: tree.html
		template: latte/tree.latte
	deprecated:
		filename: deprecated.html
		template: latte/deprecated.latte
	todo:
		filename: todo.html
		template: latte/todo.latte
	sitemap:
		filename: sitemap.xml
		template: latte/sitemap.xml.latte
	opensearch:
		filename: opensearch.xml
		template: latte/opensearch.xml.latte
	robots:
		filename: robots.txt
		template: latte/robots.txt.latte
</code>
