### ISSUE TITLE
Exception thrown generating document 

### ISSUE THREAD

**Issue by awalls** [ApiGen/ApiGen#564]
I'm trying to upgrade to ApiGen v4.0 and running via the phar archive however I am getting an error message when I try to run the ApiGen command:

apigen.phar generate --config apigen.myapp.neon --debug
 
```
exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in phar:///opt/myapp/scripts/docs/php/apigen.phar/src/ApiGen/Configuration/ConfigurationOptionsResolver.php:181
Stack trace:
#0 phar:///opt/myapp/scripts/docs/php/apigen.phar/src/ApiGen/Configuration/ConfigurationOptionsResolver.php(181): Tracy\Debugger::_errorHandler(2, 'Invalid argumen...', 'phar:///opt/sho...', 181, Array)
#1 [internal function]: ApiGen\Configuration\ConfigurationOptionsResolver->ApiGen\Configuration\{closure}(Object(Symfony\Component\OptionsResolver\OptionsResolver), NULL)
#2 phar:///opt/myapp/scripts/docs/php/apigen.phar/vendor/symfony/options-resolver/Symfony/Component/OptionsResolver/OptionsResolver.php(932): call_user_func(Object(Closure), Object(Symfony\Component\OptionsResolver\OptionsResolver), NULL)
#3 phar:///opt/myapp/scripts/docs/php/apigen.phar/vendor/symfony/options-resolver/Symfony/Component/OptionsResolver/OptionsResolver.php(769): Symfony\Component\OptionsResolver\OptionsResolver->offsetGet('skipDocPath')
#4 phar:///opt/myapp/scripts/docs/php/apigen.phar/src/ApiGen/Configuration/ConfigurationOptionsResolver.php(97): Symfony\Component\OptionsResolver\OptionsResolver->resolve(Array)
#5 phar:///opt/myapp/scripts/docs/php/apigen.phar/src/ApiGen/Configuration/Configuration.php(55): ApiGen\Configuration\ConfigurationOptionsResolver->resolve(Array)
#6 phar:///opt/myapp/scripts/docs/php/apigen.phar/src/ApiGen/Command/GenerateCommand.php(206): ApiGen\Configuration\Configuration->resolveOptions(Array)
#7 phar:///opt/myapp/scripts/docs/php/apigen.phar/src/ApiGen/Command/GenerateCommand.php(139): ApiGen\Command\GenerateCommand->prepareOptions(Array)
#8 phar:///opt/myapp/scripts/docs/php/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(252): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///opt/myapp/scripts/docs/php/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///opt/myapp/scripts/docs/php/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateCommand), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///opt/myapp/scripts/docs/php/apigen.phar/src/ApiGen/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///opt/myapp/scripts/docs/php/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///opt/myapp/scripts/docs/php/apigen.phar/src/ApiGen/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#14 phar:///opt/myapp/scripts/docs/php/apigen.phar/src/apigen.php(52): ApiGen\Console\Application->run()
#15 /opt/myapp/scripts/docs/php/apigen.phar(12): require('phar:///opt/sho...')
#16 {main}
```

The neon config file above is:
```
# Source file or directory to parse
source: [/opt/myapp/www/application/controllers,
         /opt/myapp/www/application/config,
         /opt/myapp/www/application/core,
         /opt/myapp/www/application/helpers,
         /opt/myapp/www/application/hooks,
         /opt/myapp/www/application/libraries,
         /opt/myapp/www/application/models]
# Directory where to save the generated documentation
destination: /opt/myapp/www/docs/php
# List of allowed file extensions
extensions: [php]
# Mask to exclude file or directory from processing
exclude:
# Don't generate documentation for classes from file or directory with this mask
skipDocPath:
# Character set of source files
charset: auto
# Main project name prefix
main: 

# Title of generated documentation
title: myapp Application
# Documentation base URL
baseUrl: http://docs.myapp.local/php
# Google Custom Search ID
googleCseId:
# Google Analytics tracking code
googleAnalytics:
# Template config file
templateConfig: '/opt/myapp/vendor/apigen/theme-bootstrap/src/config.neon'
# Grouping of classes
groups: auto

# Generate documentation for methods and properties with given access level
accessLevels: [private, public, protected]
# Generate documentation for elements marked as internal and display internal documentation parts
internal: No
# Generate documentation for PHP internal classes
php: Yes
# Generate tree view of classes, interfaces and exceptions
tree: Yes
# Generate documentation for deprecated classes, methods, properties and constants
deprecated: Yes
# Generate documentation of tasks
todo: Yes
# Generate highlighted source code files
sourceCode: Yes
# Add a link to download documentation as a ZIP archive
download: Yes

# Don't display scanning and generating messages
quiet: No
# Display additional information in case of an error
debug: No
```

Any ideas? 
Thanks.

**Comment by TomasVotruba** [comment]
First, what version of PHP do you use?

**Comment by awalls** [comment]
Using PHP 5.4.37 and running via the PHAR but using the Bootstrap theme installed via Composer. 

I've tried this with the 4.1 beta PHAR and get the same issue.

**Comment by TomasVotruba** [comment]
I've probably found the bug. Please try last version using `compopser require apigen/apigen`

**Comment by awalls** [comment]
Ok, I'll try this via Composer to see if it works but I'd prefer to use the PHAR file longer term are there are too many dependencies to install via Composer.

**Comment by TomasVotruba** [comment]
It will be definitely in 4.1.

In 4.0 when I find the time.
