### ISSUE TITLE
Setting the project's root (.) as destination deletes everything.

### ISSUE THREAD

**Issue by malkusch** [ApiGen/ApiGen#574]
Hi
I'm using since quiet a while `.` as destination for [generating my documentation](https://github.com/malkusch/php-mock/tree/gh-pages):
```
destination: .
source:
    - vendor/malkusch/php-mock/classes/
```
Last time when I ran `./vendor/bin/apigen generate` successfully was with ApiGen-4.0.0-RC4. Today I used v4.0.1. Well, it deleted everything inside the current working directory including hidden folders like .git.

I've set up a small test case for you:
1. `git clone --single-branch -b delete-everything https://github.com/malkusch/ApiGen.git`
2. `cd ApiGen`
3. `make`

Instead of `make` you could also run:
1. `composer update`
2. `./vendor/bin/apigen generate`

The result is that everything in the current working directory is deleted. Well, apigen fails because of that as well.

**Comment by malkusch** [comment]
I'm trying to investigate a bit and here's also an interesting remark: If I would remove the write permission for the directory's content (`chmod -w .git/ * -R`) `generate` will successfully generate my documentation without any notice.

But if I add the `--debug` flag I get to the stack trace:
```
exception 'ErrorException' with message 'unlink(/home/malkusch/workspace/oss/ApiGen/.git/refs/heads/delete-everything): Permission denied' in /home/malkusch/workspace/oss/ApiGen/vendor/apigen/apigen/src/ApiGen/FileSystem/FileSystem.php:64
Stack trace:
#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(/home/ma...', '/home/malkusch/...', 64, Array)
#1 /home/malkusch/workspace/oss/ApiGen/vendor/apigen/apigen/src/ApiGen/FileSystem/FileSystem.php(64): unlink('/home/malkusch/...')
#2 /home/malkusch/workspace/oss/ApiGen/vendor/apigen/apigen/src/ApiGen/Command/GenerateCommand.php(171): ApiGen\FileSystem\FileSystem::purgeDir('/home/malkusch/...')
#3 /home/malkusch/workspace/oss/ApiGen/vendor/apigen/apigen/src/ApiGen/Command/GenerateCommand.php(141): ApiGen\Command\GenerateCommand->generate(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/malkusch/workspace/oss/ApiGen/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/malkusch/workspace/oss/ApiGen/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/malkusch/workspace/oss/ApiGen/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateCommand), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/malkusch/workspace/oss/ApiGen/vendor/apigen/apigen/src/ApiGen/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/malkusch/workspace/oss/ApiGen/vendor/symfony/console/Symfony/Component/Console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/malkusch/workspace/oss/ApiGen/vendor/apigen/apigen/src/ApiGen/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#10 /home/malkusch/workspace/oss/ApiGen/vendor/apigen/apigen/src/apigen.php(52): ApiGen\Console\Application->run()
#11 /home/malkusch/workspace/oss/ApiGen/vendor/apigen/apigen/bin/apigen(4): require('/home/malkusch/...')
#12 {main}

**Comment by malkusch** [comment]
I closed this as I see now that it was always the intention to delete the content of the source directory. I'll sadly move my API documentation into a separate folder.

**Comment by TomasVotruba** [comment]
Hi, this behavior will be changed in 4.1, see: https://github.com/ApiGen/ApiGen/issues/550

How do you like that?

**Comment by malkusch** [comment]
Well, I moved already my documentation into a dedicated folder. But for me it was a suprise that apigen is deleting the destination. Now, I can easily live with that, but at some point I think the user should have the knowledge about that behaviour. So yes, a question prior deleting would be nice.

**Comment by TomasVotruba** [comment]
:+1: Thanks
