### ISSUE TITLE
ApiGen does not handle overwriting same abstract method via different traits

### ISSUE THREAD

**Issue by NikolaySl** [ApiGen/ApiGen#620]
This code:

``` php
Trait X {
    abstract public function a ();
}

Trait XX {
    abstract public function a ();
}

class Y {
    public function a() {
        echo "works!!!";
        return $this;
    }
}

class Z extends Y {
    use X;
    use XX;
}

$b = new Z();
$b->a();
```

Works perfectly. But apigen 4.1.0 gives next (command `apigen generate -s test.php -d out --debug`):

```
exception 'TokenReflection\Exception\RuntimeException' with message 'Trait method "a" was already imported.' in /home/nslyunkov/.composer/vendor/andrewsville/php-token-reflection/TokenReflection/ReflectionClass.php:734
Stack trace:
#0 /home/nslyunkov/.composer/vendor/andrewsville/php-token-reflection/TokenReflection/ReflectionClass.php(607): TokenReflection\ReflectionClass->getTraitMethods()
#1 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Reflection/ReflectionClass.php(149): TokenReflection\ReflectionClass->getMethods(768)
#2 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Reflection/Extractors/ClassTraitElementsExtractor.php(152): ApiGen\Reflection\ReflectionClass->getMethods()
#3 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Reflection/ReflectionClass.php(678): ApiGen\Reflection\Extractors\ClassTraitElementsExtractor->getUsedMethods()
#4 /home/nslyunkov/.composer/vendor/nette/utils/src/Utils/ObjectMixin.php(139): ApiGen\Reflection\ReflectionClass->getUsedMethods()
#5 /home/nslyunkov/.composer/vendor/nette/utils/src/Utils/Object.php(125): Nette\Utils\ObjectMixin::get(Object(ApiGen\Reflection\ReflectionClass), 'usedMethods')
#6 /tmp/_apigen/cache/latte/vendor-apigen-theme-default-src-class-latte-Template9a25fa2e9bd41675aae9127a73872368.php(173): Nette\Object->__get('usedMethods')
#7 /home/nslyunkov/.composer/vendor/latte/latte/src/Latte/Macros/BlockMacrosRuntime.php(32): _lb9ea91129d8_content(Object(stdClass), Array)
#8 /tmp/_apigen/cache/latte/vendor-apigen-theme-default-src-layout-latte-Template2dae93acfba1402db65a4e4be5890fbf.php(222): Latte\Macros\BlockMacrosRuntime::callBlock(Object(stdClass), 'content', Array)
#9 /home/nslyunkov/.composer/vendor/latte/latte/src/Latte/Engine.php(96): Template2dae93acfba1402db65a4e4be5890fbf->render()
#10 /home/nslyunkov/.composer/vendor/latte/latte/src/Latte/Template.php(93): Latte\Engine->render('/home/nslyunkov...', Array)
#11 /tmp/_apigen/cache/latte/vendor-apigen-theme-default-src-class-latte-Template9a25fa2e9bd41675aae9127a73872368.php(661): Latte\Template->renderChildTemplate('@layout.latte', Array)
#12 /home/nslyunkov/.composer/vendor/latte/latte/src/Latte/Engine.php(96): Template9a25fa2e9bd41675aae9127a73872368->render()
#13 /home/nslyunkov/.composer/vendor/latte/latte/src/Latte/Engine.php(108): Latte\Engine->render('/home/nslyunkov...', Array)
#14 /home/nslyunkov/.composer/vendor/nette/application/src/Bridges/ApplicationLatte/Template.php(64): Latte\Engine->renderToString('/home/nslyunkov...', Array)
#15 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Templating/Template.php(38): Nette\Bridges\ApplicationLatte\Template->__toString()
#16 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Generator/TemplateGenerators/ClassElementGenerator.php(65): ApiGen\Templating\Template->save()
#17 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Generator/GeneratorQueue.php(39): ApiGen\Generator\TemplateGenerators\ClassElementGenerator->generate()
#18 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Command/GenerateCommand.php(184): ApiGen\Generator\GeneratorQueue->run()
#19 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Command/GenerateCommand.php(151): ApiGen\Command\GenerateCommand->generate(Array)
#20 /home/nslyunkov/.composer/vendor/symfony/console/Command/Command.php(259): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/nslyunkov/.composer/vendor/symfony/console/Application.php(878): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/nslyunkov/.composer/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateCommand), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/nslyunkov/.composer/vendor/symfony/console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#26 /home/nslyunkov/.composer/vendor/apigen/apigen/bin/apigen(36): ApiGen\Console\Application->run()
#27 {main}

Next exception 'ErrorException' with message 'Exception in Nette\Bridges\ApplicationLatte\Template::__toString(): Trait method "a" was already imported. in /home/nslyunkov/.composer/vendor/andrewsville/php-token-reflection/TokenReflection/ReflectionClass.php:734' in /home/nslyunkov/.composer/vendor/nette/application/src/Bridges/ApplicationLatte/Template.php:69
Stack trace:
#0 [internal function]: Tracy\Debugger::errorHandler(256, 'Exception in Ne...', '/home/nslyunkov...', 69, Array)
#1 /home/nslyunkov/.composer/vendor/nette/application/src/Bridges/ApplicationLatte/Template.php(69): trigger_error('Exception in Ne...', 256)
#2 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Templating/Template.php(38): Nette\Bridges\ApplicationLatte\Template->__toString()
#3 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Generator/TemplateGenerators/ClassElementGenerator.php(65): ApiGen\Templating\Template->save()
#4 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Generator/GeneratorQueue.php(39): ApiGen\Generator\TemplateGenerators\ClassElementGenerator->generate()
#5 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Command/GenerateCommand.php(184): ApiGen\Generator\GeneratorQueue->run()
#6 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Command/GenerateCommand.php(151): ApiGen\Command\GenerateCommand->generate(Array)
#7 /home/nslyunkov/.composer/vendor/symfony/console/Command/Command.php(259): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/nslyunkov/.composer/vendor/symfony/console/Application.php(878): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/nslyunkov/.composer/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateCommand), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/nslyunkov/.composer/vendor/symfony/console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/nslyunkov/.composer/vendor/apigen/apigen/src/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#13 /home/nslyunkov/.composer/vendor/apigen/apigen/bin/apigen(36): ApiGen\Console\Application->run()
#14 {main}
Unable to log error: Directory is not specified.
```

Here is output of `apigen --version` : `ApiGen version 4.1.0`

**Comment by shadowhand** [comment]
I too have this problem with [equip/structure](https://github.com/equip/structure):

```
 % apigen generate -s src -d docs                                                                                                                       
Scanning sources and parsing

Trait method "toArray" was already imported.
```
