### ISSUE TITLE
Call to undefined function ApiGen\Charset\Configuration\mb_list_encodings()

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ApiGen#625]
I got this error when I try to generate:

```
[nmartell@localhost php_nml]$ apigen generate --debug

Fatal error: Call to undefined function ApiGen\Charset\Configuration\mb_list_encodings() in phar:///usr/local/bin/apigen/src/Charset/Configuration/CharsetOptionsResolver.php on line 102
exception 'ErrorException' with message 'Call to undefined function ApiGen\Charset\Configuration\mb_list_encodings()' in phar:///usr/local/bin/apigen/src/Charset/Configuration/CharsetOptionsResolver.php:102
Stack trace:
#0 [internal function]: Tracy\Debugger::shutdownHandler()
#1 {main}
Unable to log error: Directory is not specified.
```

```
[nmartell@localhost php_nml]$ apigen --version
ApiGen version 4.1.0
[nmartell@localhost php_nml]$ which apigen
/usr/local/bin/apigen
```

**Comment by nelson6e65** [comment]
**Maybe solved?**

I don't know if is reated or whatever... When I use composer version instead, I got this error:

```
[nmartell@localhost php_nml]$ php vendor/bin/apigen generate --debug
Scanning sources and parsing
Found 15 classes, 0 constants and 3 functions
Destination is not empty. Do you want to erase it? [yes] 
Generating API documentation
 15/42 [==========>-----------------]  35% 2 secs/6 secs 12.0 MiB <!DOCTYPE html>

. . .

<div id="content" class="function">
	<h1>Function nml_msg</h1>


	<div class="description">
	<p>Busca un mensaje único traducido en el dominio 'nml'.
El mensaje puede contener cadenas de formato.</p>
	</div>

	<div class="info">
		
		
				<b>Copyright:</b>
				2015 Nelson Martell<br>
				<b>License:</b>
				<a href="http://www.opensource.org/licenses/mit-license.php">The MIT License (MIT)</a><br>
				<b>See:</b>
				dgettext<br>
				<b>See:</b>
				exception 'ErrorException' with message 'Argument 2 passed to ApiGen\Generator\Resolvers\ElementResolver::resolveContextForClassProperty() must be an instance of ApiGen\Reflection\ReflectionClass, instance of ApiGen\Reflection\ReflectionFunction given, called in /opt/lampp/htdocs/php_nml/vendor/apigen/apigen/src/Generator/Resolvers/ElementResolver.php on line 155 and defined' in /opt/lampp/htdocs/php_nml/vendor/apigen/apigen/src/Generator/Resolvers/ElementResolver.php:300
Stack trace:
#0 /opt/lampp/htdocs/php_nml/vendor/apigen/apigen/src/Generator/Resolvers/ElementResolver.php(300): Tracy\Debugger::errorHandler(4096, 'Argument 2 pass...', '/opt/lampp/htdo...', 300, Array)
#1 /opt/lampp/htdocs/php_nml/vendor/apigen/apigen/src/Generator/Resolvers/ElementResolver.php(155): ApiGen\Generator\Resolvers\ElementResolver->resolveContextForClassProperty('String::format', Object(ApiGen\Reflection\ReflectionFunction), 6)
#2 /opt/lampp/htdocs/php_nml/vendor/apigen/apigen/src/Templating/Filters/UrlFilters.php(98): ApiGen\Generator\Resolvers\ElementResolver->resolveElement('String::format', Object(ApiGen\Reflection\ReflectionFunction), NULL)

. . .

```

That file ([/src/functions.php](https://github.com/nelson6e65/php_nml/blob/4fe56800ac342421eb1d0b0aa1a8f9a255494b77/src/functions.php)) contains only global functions: In that error block, I noticed was in `@see` tags (lines [33](https://github.com/nelson6e65/php_nml/blob/4fe56800ac342421eb1d0b0aa1a8f9a255494b77/src/functions.php#L33), [61](https://github.com/nelson6e65/php_nml/blob/4fe56800ac342421eb1d0b0aa1a8f9a255494b77/src/functions.php#L61) and [82](https://github.com/nelson6e65/php_nml/blob/4fe56800ac342421eb1d0b0aa1a8f9a255494b77/src/functions.php#L82)).

When I remove that lines, `generate` runs fine, using

```
php vendor/bin/apigen generate --debug
Scanning sources and parsing
Found 15 classes, 0 constants and 3 functions
Destination is not empty. Do you want to erase it? [yes] 
Generating API documentation
 42/42 [============================] 100% 3 secs/3 secs 12.0 MiB  - Finished!
```

and 

```
[nmartell@localhost php_nml]$ apigen generate --debug
Scanning sources and parsing
Found 15 classes, 0 constants and 3 functions
Destination is not empty. Do you want to erase it? [yes] 
Generating API documentation
 42/42 [============================] 100% 3 secs/3 secs 11.5 MiB  - Finished!
```

**That was a bad format `@see` tags?**
For now, I fixed apigen generation removing that @see tags, but.... *Why did that happenend? It was my DocBlock bad formatted? Should not be catched that exceptions to avoid this problem?* :confused:

**Comment by jadb** [comment]
Thanks for reporting this. You are right, it should be caught, linked to or just ignored.

**Comment by jadb** [comment]
As I was reviewing the remaining issues, I found #602. I am closing this one in favour of the other one. The invitation to submit a failing test and/or PR is still open though!

**Comment by nelson6e65** [comment]
@jadb A failing test? o.o
