### ISSUE TITLE
ApiGen crashes with Kdyby/Events

### ISSUE THREAD

**Issue by wandersonwhcr** [ApiGen/ApiGen#695]
Hello,

I'm trying to install `apigen` in my [wandersonwhcr/balance](//github.com/wandersonwhcr/balance) project using `composer`.

```
composer require --dev --no-update 'apigen/apigen:4.1.*'
composer update 'apigen/apigen'
```

Executing `php vendor/bin/apigen --debug` I found this problem:

```
Fatal error: Class Kdyby\Events\SymfonyDispatcher contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\EventDispatcher\EventDispatcherInterface::getListenerPriority) in /vagrant/vendor/kdyby/events/src/Kdyby/Events/SymfonyDispatcher.php on line 94

Call Stack:
    0.0020     122104   1. {main}() /vagrant/vendor/apigen/apigen/bin/apigen:0
    0.1898    1433112   2. Nette\Configurator->createContainer() /vagrant/vendor/apigen/apigen/bin/apigen:31
    0.1938    1454688   3. Nette\DI\ContainerLoader->load() /vagrant/vendor/nette/bootstrap/src/Bootstrap/Configurator.php:218
    0.1941    1454892   4. Nette\DI\ContainerLoader->loadFile() /vagrant/vendor/nette/di/src/DI/ContainerLoader.php:41
    0.1945    1455968   5. Nette\DI\ContainerLoader->generate() /vagrant/vendor/nette/di/src/DI/ContainerLoader.php:76
    0.2073    1690312   6. call_user_func_array:{/vagrant/vendor/nette/di/src/DI/ContainerLoader.php:111}() /vagrant/vendor/nette/di/src/DI/ContainerLoader.php:111
    0.2073    1690592   7. Nette\Configurator->generateContainer() /vagrant/vendor/nette/di/src/DI/ContainerLoader.php:111
    0.3046    2087132   8. Nette\DI\Compiler->compile() /vagrant/vendor/nette/bootstrap/src/Bootstrap/Configurator.php:264
    0.7096    3969628   9. Nette\DI\Compiler->generateCode() /vagrant/vendor/nette/di/src/DI/Compiler.php:139
    0.7096    3969988  10. Nette\DI\ContainerBuilder->prepareClassList() /vagrant/vendor/nette/di/src/DI/Compiler.php:205
    1.1439    5561000  11. Nette\DI\ContainerBuilder->resolveServiceClass() /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php:316
    1.1439    5561204  12. Nette\DI\ContainerBuilder->resolveEntityClass() /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php:422
    1.1440    5561260  13. class_exists() /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php:474
    1.1440    5561448  14. spl_autoload_call() /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php:474
    1.1440    5561488  15. Composer\Autoload\ClassLoader->loadClass() /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php:474
    1.1448    5561592  16. Composer\Autoload\includeFile() /vagrant/vendor/composer/ClassLoader.php:301
    1.1478    5569884  17. include('/vagrant/vendor/kdyby/events/src/Kdyby/Events/SymfonyDispatcher.php') /vagrant/vendor/composer/ClassLoader.php:412

ErrorException: Class Kdyby\Events\SymfonyDispatcher contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\EventDispatcher\EventDispatcherInterface::getListenerPriority) in /vagrant/vendor/kdyby/events/src/Kdyby/Events/SymfonyDispatcher.php:94
Stack trace:
#0 /vagrant/vendor/composer/ClassLoader.php(412): *unknown*()
#1 /vagrant/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile()
#2 /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php(474): Composer\Autoload\ClassLoader->loadClass()
#3 /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php(474): spl_autoload_call()
#4 /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php(474): class_exists()
#5 /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php(422): Nette\DI\ContainerBuilder->resolveEntityClass()
#6 /vagrant/vendor/nette/di/src/DI/ContainerBuilder.php(316): Nette\DI\ContainerBuilder->resolveServiceClass()
#7 /vagrant/vendor/nette/di/src/DI/Compiler.php(205): Nette\DI\ContainerBuilder->prepareClassList()
#8 /vagrant/vendor/nette/di/src/DI/Compiler.php(139): Nette\DI\Compiler->generateCode()
#9 /vagrant/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(264): Nette\DI\Compiler->compile()
#10 /vagrant/vendor/nette/di/src/DI/ContainerLoader.php(111): Nette\Configurator->generateContainer()
#11 /vagrant/vendor/nette/di/src/DI/ContainerLoader.php(111): call_user_func_array:{/vagrant/vendor/nette/di/src/DI/ContainerLoader.php:111}()
#12 /vagrant/vendor/nette/di/src/DI/ContainerLoader.php(76): Nette\DI\ContainerLoader->generate()
#13 /vagrant/vendor/nette/di/src/DI/ContainerLoader.php(41): Nette\DI\ContainerLoader->loadFile()
#14 /vagrant/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(218): Nette\DI\ContainerLoader->load()
#15 /vagrant/vendor/apigen/apigen/bin/apigen(31): Nette\Configurator->createContainer()
#16 {main}
Unable to log error: Directory is not specified.
```

**Comment by jadb** [comment]
Can you please try upgrading to `dev-master` instead?

**Comment by jyggen** [comment]
Upgrading to `dev-master` solves the issue for me but results in the following instead:

```
Nette\InvalidStateException: Found section 'application' in configuration, but corresponding extension is missing. in /vendor/nette/di/src/DI/Compiler.php:187
Stack trace:
#0 /vendor/nette/di/src/DI/Compiler.php(137): Nette\DI\Compiler->processExtensions()
#1 /vendor/nette/bootstrap/src/Bootstrap/Configurator.php(264): Nette\DI\Compiler->compile()
#2 [internal function]: Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#3 /vendor/nette/di/src/DI/ContainerLoader.php(111): call_user_func_array(Array, Array)
#4 /vendor/nette/di/src/DI/ContainerLoader.php(76): Nette\DI\ContainerLoader->generate('Container_51f82...', Array)
#5 /vendor/nette/di/src/DI/ContainerLoader.php(41): Nette\DI\ContainerLoader->loadFile('Container_51f82...', Array)
#6 /vendor/nette/bootstrap/src/Bootstrap/Configurator.php(217): Nette\DI\ContainerLoader->load(Array, Array)
#7 /vendor/apigen/apigen/bin/apigen(39): Nette\Configurator->createContainer()
#8 {main}
Unable to log error: Directory is not specified.
```

**Comment by bolmstedt** [comment]
When updating to `dev-master`, composer removed `nette/application` and `nette/robot-loader`, both required.

**Comment by jadb** [comment]
Sorry for the delay.

Some BC were introduced in minor releases of some dependencies; which seems to have caused issues on new installations. 

Recently merged PRs should solve most issues. Please close if the new `dev-master` solves it for you.

**Comment by wandersonwhcr** [comment]
:+1:

**Comment by TomasVotruba** [comment]
Resolved, closing
